# ----------------------------------------------------
# 1. Configuração do Banco de Dados
# ----------------------------------------------------

# Comentar ou remover as linhas do H2
# %dev.quarkus.datasource.db-kind=h2
# %dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:default

# Configuração do PostgreSQL (Para ambiente de Desenvolvimento)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/equiptrackdb
quarkus.datasource.username=[BLOCKED_BY_GITHUB]
quarkus.datasource.password=[BLOCKED_BY_GITHUB]

# ----------------------------------------------------
# 2. Hibernate/Panache
# ----------------------------------------------------
# Cria as tabelas ao iniciar (útil para desenvolvimento)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true 

# ----------------------------------------------------
# 3. CORS
# ----------------------------------------------------
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# ----------------------------------------------------
# 4. Testes Contínuos
# ----------------------------------------------------
# Desabilitar testes contínuos em dev para evitar conflitos

quarkus.test.continuous-testing=disabled